# Site settings
title: SevenBits' Blog
name: SevenBits
email: contact@sevenbits.io
location: New Hampshire
company_url: https://www.sevenbits.tk/
github_url: https://github.com/SevenBits
description:
  At SevenBits, our mission is to create software,
  solutions, and products to help the world’s innovators
  accomplish everything they set out to do.
favicon: favicon.ico # Image must be in assets/images
repository: SevenBits/SevenBits.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://www.sevenbits.io/blog

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
#disque: my_disque_settings

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home
  -
    href: https://www.sevenbits.tk/
    label: My Apps

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-46715734-1'
